<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageOutputPath>$(SolutionDir)Packages/</PackageOutputPath>
        <Version>$(VersionPrefix).$(VersionSuffix)</Version>
        <TargetFrameworks>netstandard2.0;net461;net8.0</TargetFrameworks>
        <RootNamespace>Project2015To2017</RootNamespace>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <NoWarn>CS0618;CS8981;NU5125;NU1900</NoWarn>
        <PackageId>Net4x.Project2015To2017.Core</PackageId>
    </PropertyGroup>
    <PropertyGroup Condition="'$(TargetFrameworkIdentifier)'!='.NETCoreApp'">
        <!-- PathCompat.NETFramework.cs -->
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.1.0" />
        <PackageReference Include="NuGet.Configuration" Version="5.1.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="2.2.0" />
        <PackageReference Include="System.Memory" Version="4.5.3" />
        <PackageReference Include="Net4x.NuGetUtility" Version="$(NuGetUtilityVersion)" PrivateAssets="All" />
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFrameworkIdentifier)'=='.NETCoreApp'">
        <Compile Remove="PathCompat.NETFramework.cs" />
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFrameworkIdentifier)'!='.NETCoreApp'">
        <Compile Remove="PathCompat.NETCore.cs" />
    </ItemGroup>
    <PropertyGroup>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>
    <ItemGroup>
        <Content Include="README.md" Link="README.md" Pack="true" PackagePath="\README.md" />
        <Content Include="$(SolutionDir)License.txt" Link="License.txt" Pack="true" PackagePath="\License.txt" Condition="Exists('$(SolutionDir)License.txt')" />
    </ItemGroup>
</Project>