<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageOutputPath>$(SolutionDir)Packages/</PackageOutputPath>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <Version>$(VersionPrefix).$(VersionSuffix)</Version>
        <TargetFrameworks Condition="$(Pack) != 'true'">net461;net6.0</TargetFrameworks>
        <TargetFramework Condition="$(Pack) == 'true'">net6.0</TargetFramework>
        <PackAsTool Condition="$(Pack) == 'true'">True</PackAsTool>
        <PackageId>Net4x.$(ProjectName)</PackageId>
        <AssemblyName>dotnet-migrate-2017</AssemblyName>
        <PackageId>Net4x.Project2015To2017.Migrate2017.Tool</PackageId>
        <Product>Project2015To2017.Migrate2017.Tool</Product>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="DotNet.Glob" Version="3.0.5" />
        <PackageReference Include="Serilog" Version="2.8.0.$(VersionBuildSuffix)" />
        <PackageReference Include="Serilog.Enrichers.Demystify" Version="1.0.0-dev-00019" />
        <PackageReference Include="Serilog.Extensions.Logging" Version="2.0.4.$(VersionBuildSuffix)" />
        <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1.$(VersionBuildSuffix)" />
        <PackageReference Include="Net4x.NuGetUtility" Version="$(NuGetUtilityVersion)" PrivateAssets="All" />
    </ItemGroup>
    <PropertyGroup>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>
    <ItemGroup>
        <Content Include="README.md" Link="README.md" Pack="true" PackagePath="\README.md" />
        <Content Include="$(SolutionDir)License.txt" Link="License.txt" Pack="true" PackagePath="\License.txt" Condition="Exists('$(SolutionDir)License.txt')" />
    </ItemGroup>
    <Import Project="..\Project2015To2017.MigrateXXXX.Tool\Project2015To2017.MigrateXXXX.Tool.proj" />
    <ItemGroup>
        <ProjectReference Include="..\Project2015To2017.Core\Project2015To2017.Core.csproj" />
        <ProjectReference Include="..\Project2015To2017.Migrate2017.Library\Project2015To2017.Migrate2017.Library.csproj" />
        <ProjectReference Include="..\Project2015To2017\Project2015To2017.csproj" />
    </ItemGroup>
</Project>